📊 Reglas de Asociación con Apriori
🔹 Introducción

El objetivo de este análisis es descubrir patrones de compra en un conjunto de transacciones de supermercado.
Para esto se aplican técnicas de minería de reglas de asociación, que permiten responder preguntas como:

¿Qué productos suelen comprarse juntos?

¿Qué ítems aparecen con mayor frecuencia en las transacciones?

¿Qué combinaciones de productos tienen mayor soporte, confianza y lift?

In [ ]:
!pip install apyori
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
#from google.colab import files
from apyori import apriori
from mlxtend.frequent_patterns import apriori as mlx_apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=efab0d222b70d0092fa15e3a19a1385603fb7ac5d5f34536c93e93321800cb2f
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [2]:
!pip list

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Package                            Version
---------------------------------- --------------------
absl-py                            1.4.0
accelerate                         1.2.1
aiohappyeyeballs                   2.4.4
aiohttp                            3.11.10
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.19
albumentations                     1.4.20
altair                             5.5.0
annotated-types                    0.7.0
anyio                              3.7.1
apyori                             1.1.2
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.5.1
arviz                              0.20.0
astropy                            6.1.7
astropy-iers-data                  0.2024.12.16.0.35.48
astunparse                         1.6.3
async-timeout                      4.0.3
atpublic                           4.1.0
attrs                              24.3.0
audioread                          3.0.1
autograd                           1.7.0
babel                              2.16.0
backcall                           0.2.0
beautifulsoup4                     4.12.3
bigframes                          1.29.0
bigquery-magics                    0.4.0
bleach                             6.2.0
blinker                            1.9.0
blis                               0.7.11
blosc2                             2.7.1
bokeh                              3.6.2
Bottleneck                         1.4.2
bqplot                             0.12.43
branca                             0.8.1
CacheControl                       0.14.1
cachetools                         5.5.0
catalogue                          2.0.10
certifi                            2024.12.14
cffi                               1.17.1
chardet                            5.2.0
charset-normalizer                 3.4.0
chex                               0.1.88
clarabel                           0.9.0
click                              8.1.7
cloudpathlib                       0.20.0
cloudpickle                        3.1.0
cmake                              3.31.2
cmdstanpy                          1.2.5
colorcet                           3.1.0
colorlover                         0.3.0
colour                             0.1.5
community                          1.0.0b1
confection                         0.1.5
cons                               0.4.6
contourpy                          1.3.1
cryptography                       43.0.3
cuda-python                        12.2.1
cudf-cu12                          24.10.1
cufflinks                          0.17.3
cupy-cuda12x                       12.2.0
cvxopt                             1.3.2
cvxpy                              1.6.0
cycler                             0.12.1
cymem                              2.0.10
Cython                             3.0.11
dask                               2024.10.0
datascience                        0.17.6
db-dtypes                          1.3.1
dbus-python                        1.2.18
debugpy                            1.8.0
decorator                          4.4.2
defusedxml                         0.7.1
Deprecated                         1.2.15
diffusers                          0.31.0
distro                             1.9.0
dlib                               19.24.2
dm-tree                            0.1.8
docker-pycreds                     0.4.0
docstring_parser                   0.16
docutils                           0.21.2
dopamine_rl                        4.1.0
duckdb                             1.1.3
earthengine-api                    1.4.3
easydict                           1.13
editdistance                       0.8.1
eerepr                             0.0.4
einops                             0.8.0
en-core-web-sm                     3.7.1
entrypoints                        0.4
et_xmlfile                         2.0.0
etils                              1.11.0
etuples                            0.3.9
eval_type_backport                 0.2.0
exceptiongroup                     1.2.2
fastai                             2.7.18
fastcore                           1.7.27
fastdownload                       0.0.7
fastjsonschema                     2.21.1
fastprogress                       1.0.3
fastrlock                          0.8.2
filelock                           3.16.1
firebase-admin                     6.6.0
Flask                              3.1.0
flatbuffers                        24.3.25
flax                               0.8.5
folium                             0.19.2
fonttools                          4.55.3
frozendict                         2.4.6
frozenlist                         1.5.0
fsspec                             2024.10.0
future                             1.0.0
gast                               0.6.0
gcsfs                              2024.10.0
GDAL                               3.6.4
gdown                              5.2.0
geemap                             0.35.1
gensim                             4.3.3
geocoder                           1.38.1
geographiclib                      2.0
geopandas                          1.0.1
geopy                              2.4.1
gin-config                         0.5.0
gitdb                              4.0.11
GitPython                          3.1.43
glob2                              0.7
google                             2.0.3
google-ai-generativelanguage       0.6.10
google-api-core                    2.19.2
google-api-python-client           2.155.0
google-auth                        2.27.0
google-auth-httplib2               0.2.0
google-auth-oauthlib               1.2.1
google-cloud-aiplatform            1.74.0
google-cloud-bigquery              3.25.0
google-cloud-bigquery-connection   1.17.0
google-cloud-bigquery-storage      2.27.0
google-cloud-bigtable              2.27.0
google-cloud-core                  2.4.1
google-cloud-datastore             2.20.2
google-cloud-firestore             2.19.0
google-cloud-functions             1.19.0
google-cloud-iam                   2.17.0
google-cloud-language              2.16.0
google-cloud-pubsub                2.27.1
google-cloud-resource-manager      1.14.0
google-cloud-storage               2.19.0
google-cloud-translate             3.19.0
google-colab                       1.0.0
google-crc32c                      1.6.0
google-genai                       0.2.2
google-generativeai                0.8.3
google-pasta                       0.2.0
google-resumable-media             2.7.2
googleapis-common-protos           1.66.0
googledrivedownloader              0.4
graphviz                           0.20.3
greenlet                           3.1.1
grpc-google-iam-v1                 0.13.1
grpcio                             1.68.1
grpcio-status                      1.62.3
gspread                            6.0.2
gspread-dataframe                  3.3.1
gym                                0.25.2
gym-notices                        0.0.8
h11                                0.14.0
h5netcdf                           1.4.1
h5py                               3.12.1
holidays                           0.63
holoviews                          1.20.0
html5lib                           1.1
httpcore                           1.0.7
httpimport                         1.4.0
httplib2                           0.22.0
httpx                              0.28.1
huggingface-hub                    0.27.0
humanize                           4.11.0
hyperopt                           0.2.7
ibis-framework                     9.2.0
idna                               3.10
imageio                            2.36.1
imageio-ffmpeg                     0.5.1
imagesize                          1.4.1
imbalanced-learn                   0.12.4
imgaug                             0.4.0
immutabledict                      4.2.1
importlib_metadata                 8.5.0
importlib_resources                6.4.5
imutils                            0.5.4
inflect                            7.4.0
iniconfig                          2.0.0
intel-cmplr-lib-ur                 2025.0.4
intel-openmp                       2025.0.4
ipyevents                          2.0.2
ipyfilechooser                     0.6.0
ipykernel                          5.5.6
ipyleaflet                         0.19.2
ipyparallel                        8.8.0
ipython                            7.34.0
ipython-genutils                   0.2.0
ipython-sql                        0.5.0
ipytree                            0.2.2
ipywidgets                         7.7.1
itsdangerous                       2.2.0
jax                                0.4.33
jax-cuda12-pjrt                    0.4.33
jax-cuda12-plugin                  0.4.33
jaxlib                             0.4.33
jeepney                            0.7.1
jellyfish                          1.1.0
jieba                              0.42.1
Jinja2                             3.1.4
jiter                              0.8.2
joblib                             1.4.2
jsonpatch                          1.33
jsonpickle                         4.0.1
jsonpointer                        3.0.0
jsonschema                         4.23.0
jsonschema-specifications          2024.10.1
jupyter-client                     6.1.12
jupyter-console                    6.1.0
jupyter_core                       5.7.2
jupyter-leaflet                    0.19.2
jupyter-server                     1.24.0
jupyterlab_pygments                0.3.0
jupyterlab_widgets                 3.0.13
kaggle                             1.6.17
kagglehub                          0.3.5
keras                              3.5.0
keyring                            23.5.0
kiwisolver                         1.4.7
langchain                          0.3.12
langchain-core                     0.3.25
langchain-text-splitters           0.3.3
langcodes                          3.5.0
langsmith                          0.2.3
language_data                      1.3.0
launchpadlib                       1.10.16
lazr.restfulclient                 0.14.4
lazr.uri                           1.0.6
lazy_loader                        0.4
libclang                           18.1.1
libcudf-cu12                       24.10.1
librosa                            0.10.2.post1
lightgbm                           4.5.0
linkify-it-py                      2.0.3
llvmlite                           0.43.0
locket                             1.0.0
logical-unification                0.4.6
lxml                               5.3.0
marisa-trie                        1.2.1
Markdown                           3.7
markdown-it-py                     3.0.0
MarkupSafe                         3.0.2
matplotlib                         3.8.0
matplotlib-inline                  0.1.7
matplotlib-venn                    1.1.1
mdit-py-plugins                    0.4.2
mdurl                              0.1.2
miniKanren                         1.0.3
missingno                          0.5.2
mistune                            3.0.2
mizani                             0.13.1
mkl                                2025.0.1
ml-dtypes                          0.4.1
mlxtend                            0.23.3
more-itertools                     10.5.0
moviepy                            1.0.3
mpmath                             1.3.0
msgpack                            1.1.0
multidict                          6.1.0
multipledispatch                   1.0.0
multitasking                       0.0.11
murmurhash                         1.0.11
music21                            9.3.0
namex                              0.0.8
narwhals                           1.18.4
natsort                            8.4.0
nbclassic                          1.1.0
nbclient                           0.10.1
nbconvert                          7.16.4
nbformat                           5.10.4
ndindex                            1.9.2
nest-asyncio                       1.6.0
networkx                           3.4.2
nibabel                            5.3.2
nltk                               3.9.1
notebook                           6.5.5
notebook_shim                      0.2.4
numba                              0.60.0
numexpr                            2.10.2
numpy                              1.26.4
nvidia-cublas-cu12                 12.6.4.1
nvidia-cuda-cupti-cu12             12.6.80
nvidia-cuda-nvcc-cu12              12.6.85
nvidia-cuda-runtime-cu12           12.6.77
nvidia-cudnn-cu12                  9.6.0.74
nvidia-cufft-cu12                  11.3.0.4
nvidia-curand-cu12                 10.3.7.77
nvidia-cusolver-cu12               11.7.1.2
nvidia-cusparse-cu12               12.5.4.2
nvidia-nccl-cu12                   2.23.4
nvidia-nvjitlink-cu12              12.6.85
nvtx                               0.2.10
nx-cugraph-cu12                    24.10.0
oauth2client                       4.1.3
oauthlib                           3.2.2
openai                             1.57.4
opencv-contrib-python              4.10.0.84
opencv-python                      4.10.0.84
opencv-python-headless             4.10.0.84
openpyxl                           3.1.5
opentelemetry-api                  1.29.0
opentelemetry-sdk                  1.29.0
opentelemetry-semantic-conventions 0.50b0
opt_einsum                         3.4.0
optax                              0.2.4
optree                             0.13.1
orbax-checkpoint                   0.6.4
orjson                             3.10.12
osqp                               0.6.7.post3
packaging                          24.2
pandas                             2.2.2
pandas-datareader                  0.10.0
pandas-gbq                         0.25.0
pandas-stubs                       2.2.2.240909
pandocfilters                      1.5.1
panel                              1.5.4
param                              2.2.0
parso                              0.8.4
parsy                              2.1
partd                              1.4.2
pathlib                            1.0.1
patsy                              1.0.1
peewee                             3.17.8
peft                               0.14.0
pexpect                            4.9.0
pickleshare                        0.7.5
pillow                             11.0.0
pip                                24.1.2
platformdirs                       4.3.6
plotly                             5.24.1
plotnine                           0.14.4
pluggy                             1.5.0
ply                                3.11
polars                             1.9.0
pooch                              1.8.2
portpicker                         1.5.2
preshed                            3.0.9
prettytable                        3.12.0
proglog                            0.1.10
progressbar2                       4.5.0
prometheus_client                  0.21.1
promise                            2.3
prompt_toolkit                     3.0.48
propcache                          0.2.1
prophet                            1.1.6
proto-plus                         1.25.0
protobuf                           4.25.5
psutil                             5.9.5
psycopg2                           2.9.10
ptyprocess                         0.7.0
py-cpuinfo                         9.0.0
py4j                               0.10.9.7
pyarrow                            17.0.0
pyasn1                             0.6.1
pyasn1_modules                     0.4.1
pycocotools                        2.0.8
pycparser                          2.22
pydantic                           2.10.3
pydantic_core                      2.27.1
pydata-google-auth                 1.9.0
pydot                              3.0.3
pydotplus                          2.0.2
PyDrive                            1.3.1
PyDrive2                           1.21.3
pyerfa                             2.0.1.5
pygame                             2.6.1
pygit2                             1.16.0
Pygments                           2.18.0
PyGObject                          3.42.1
PyJWT                              2.10.1
pylibcudf-cu12                     24.10.1
pylibcugraph-cu12                  24.10.0
pylibraft-cu12                     24.10.0
pymc                               5.19.1
pymystem3                          0.2.0
pynvjitlink-cu12                   0.4.0
pyogrio                            0.10.0
Pyomo                              6.8.2
PyOpenGL                           3.1.7
pyOpenSSL                          24.2.1
pyparsing                          3.2.0
pyperclip                          1.9.0
pyproj                             3.7.0
pyshp                              2.3.1
PySocks                            1.7.1
pyspark                            3.5.3
pytensor                           2.26.4
pytest                             8.3.4
python-apt                         0.0.0
python-box                         7.3.0
python-dateutil                    2.8.2
python-louvain                     0.16
python-slugify                     8.0.4
python-utils                       3.9.1
pytz                               2024.2
pyviz_comms                        3.0.3
PyYAML                             6.0.2
pyzmq                              24.0.1
qdldl                              0.1.7.post4
ratelim                            0.1.6
referencing                        0.35.1
regex                              2024.11.6
requests                           2.32.3
requests-oauthlib                  1.3.1
requests-toolbelt                  1.0.0
requirements-parser                0.9.0
rich                               13.9.4
rmm-cu12                           24.10.0
rpds-py                            0.22.3
rpy2                               3.4.2
rsa                                4.9
safetensors                        0.4.5
scikit-image                       0.25.0
scikit-learn                       1.6.0
scipy                              1.13.1
scooby                             0.10.0
scs                                3.2.7
seaborn                            0.13.2
SecretStorage                      3.3.1
Send2Trash                         1.8.3
sentence-transformers              3.3.1
sentencepiece                      0.2.0
sentry-sdk                         2.19.2
setproctitle                       1.3.4
setuptools                         75.1.0
shap                               0.46.0
shapely                            2.0.6
shellingham                        1.5.4
simple-parsing                     0.1.6
six                                1.17.0
sklearn-pandas                     2.2.0
slicer                             0.0.8
smart-open                         7.0.5
smmap                              5.0.1
sniffio                            1.3.1
snowballstemmer                    2.2.0
soundfile                          0.12.1
soupsieve                          2.6
soxr                               0.5.0.post1
spacy                              3.7.5
spacy-legacy                       3.0.12
spacy-loggers                      1.0.5
Sphinx                             8.1.3
sphinxcontrib-applehelp            2.0.0
sphinxcontrib-devhelp              2.0.0
sphinxcontrib-htmlhelp             2.1.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               2.0.0
sphinxcontrib-serializinghtml      2.0.0
SQLAlchemy                         2.0.36
sqlglot                            25.1.0
sqlparse                           0.5.3
srsly                              2.5.0
stanio                             0.5.1
statsmodels                        0.14.4
StrEnum                            0.4.15
stringzilla                        3.11.1
sympy                              1.13.1
tables                             3.10.1
tabulate                           0.9.0
tbb                                2022.0.0
tcmlib                             1.2.0
tenacity                           9.0.0
tensorboard                        2.17.1

In [3]:
#files.upload()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [4]:
url="https://www.jacobsoft.com.mx/wp-content/uploads/2019/01/Market_Basket_Optimisation.csv"
df = pd.read_csv(url, header=None)

print(df.shape)
print(df.columns)
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(7501, 20)
Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype='int64')

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.fillna('',axis=1,inplace=True)
df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,,,,,,,,,,,,,,,,,
2,chutney,,,,,,,,,,,,,,,,,,,
3,turkey,avocado,,,,,,,,,,,,,,,,,,
4,mineral water,milk,energy bar,whole wheat rice,green tea,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,,,,,,,,,,,,,,,,,
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,,,,,,,,,,,,,,
7498,chicken,,,,,,,,,,,,,,,,,,,
7499,escalope,green tea,,,,,,,,,,,,,,,,,,
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,,,,,,,,,,,,,,,,

In [6]:
unicos=pd.unique(df.values.ravel())
print(len(unicos))
print(type(unicos))
unicos

121
<class 'numpy.ndarray'>

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array(['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes',
       'whole weat flour', 'yams', 'cottage cheese', 'energy drink',
       'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad',
       'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie',
       'spinach', 'olive oil', 'burgers', 'meatballs', 'eggs', '',
       'chutney', 'turkey', 'milk', 'energy bar', 'whole wheat rice',
       'whole wheat pasta', 'french fries', 'soup', 'light cream',
       'shallot', 'frozen vegetables', 'spaghetti', 'pet food', 'cookies',
       'cooking oil', 'champagne', 'chocolate', 'chicken', 'oil',
       'fresh tuna', 'tomatoes', 'black tea', 'extra dark chocolate',
       'protein bar', 'red wine', 'pasta', 'pepper', 'shampoo', 'rice',
       'sparkling water', 'ham', 'body spray', 'pancakes',
       'grated cheese', 'white wine', 'toothpaste', 'parmesan cheese',
       'fresh bread', 'ground beef', 'escalope', 'herb & pepper',
       'tomato sauce', 'magazines', 'strawberries', 'strong cheese',
       'pickles', 'cake', 'hot dogs', 'brownies', 'cereals',
       'clothes accessories', 'bug spray', 'muffins', 'light mayo',
       'gums', 'soda', 'cider', 'corn', 'yogurt cake', 'mint', 'butter',
       'asparagus', 'french wine', 'salt', 'tea', 'barbecue sauce',
       'mayonnaise', 'zucchini', 'carrots', 'mushroom cream sauce',
       'candy bars', 'chili', 'mashed potato', 'nonfat milk',
       'water spray', 'chocolate bread', 'mint green tea', 'eggplant',
       'blueberries', 'bacon', 'fromage blanc', 'gluten free bar',
       'dessert wine', 'flax seed', 'hand protein bar', 'sandwich',
       'babies food', 'melons', 'cauliflower', 'green beans', 'ketchup',
       'bramble', 'burger sauce', 'oatmeal', ' asparagus', 'cream',
       'napkins'], dtype=object)

In [7]:
# vamos a cargar los valores existentes en una lista pues apyori requiere que la
# longitud de todas las transacciones sea la misma (los nan no son problema, puede gestionarlos)

transactions = []
for i in range(0, 7501):
    transactions.append([str(df.values[i,j]) for j in range(0, 20)])
transactions[:5]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers',
  'meatballs',
  'eggs',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['chutney',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['turkey',
  'avocado',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['mineral water',
  'milk',
  'energy bar',
  'whole wheat rice',
  'green tea',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '']]

In [8]:
# a ver qué tenemos acá
print(len(transactions))
print(transactions[1])
print(len(transactions[23]))

7501
['burgers', 'meatballs', 'eggs', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
20

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [9]:
transactions[0][5]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

'whole weat flour'

In [10]:
# Training Apriori on the dataset
rules = apriori(transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [11]:
type(rules)   # ajá

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

generator

In [12]:
rules

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [13]:
# Resultados
results = list(rules)
print(len(results))
muestra=results[0]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

160

In [14]:
print(len(muestra))
muestra

3

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)])

In [15]:
muestra[0]   # RelationRecord

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

frozenset({'chicken', 'light cream'})

In [16]:
muestra[1]    # support

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

0.004532728969470737

In [17]:
muestra[2]    # tiene 4 elementos, lista embebida

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]

In [18]:
muestra[2][0][0]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

frozenset({'light cream'})

In [19]:
muestra[2][0][1]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

frozenset({'chicken'})

In [20]:
muestra[2][0][2]   # confidence

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

0.29059829059829057

In [21]:
muestra[2][0][3]    #lift

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

4.84395061728395

In [22]:
# definimos una función para acomodar los grupos frecuentes para verlos después

def inspect(results):
    izq          = [tuple(result[2][0][0])[0] for result in results]
    der          = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(izq, der, supports, confidences, lifts))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
liston=inspect(results)
liston[0]

# ('light cream',     # antecedente
#  'chicken',         # consecuente
#  0.0045327,         # support
#  0.2906,            # confidence
#  4.8440             # lift
# )

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

('light cream',
 'chicken',
 0.004532728969470737,
 0.29059829059829057,
 4.84395061728395)

In [24]:
liston[:2]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

[('light cream',
  'chicken',
  0.004532728969470737,
  0.29059829059829057,
  4.84395061728395),
 ('mushroom cream sauce',
  'escalope',
  0.005732568990801226,
  0.3006993006993007,
  3.790832696715049)]

In [25]:
# Este comaNdo crea un frame para ver los datos en 'results'
resultDataFrame=pd.DataFrame(inspect(results),
                columns=['izq','der','support','confidence','lift'])
resultDataFrame

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                      izq          der   support  confidence      lift
0             light cream      chicken  0.004533    0.290598  4.843951
1    mushroom cream sauce     escalope  0.005733    0.300699  3.790833
2                   pasta     escalope  0.005866    0.372881  4.700812
3           fromage blanc        honey  0.003333    0.245098  5.164271
4           herb & pepper  ground beef  0.015998    0.323450  3.291994
..                    ...          ...       ...         ...       ...
155             olive oil               0.003066    0.216981  3.632981
156              pancakes               0.003066    0.211009  3.532991
157              tomatoes               0.003066    0.261364  4.376091
158                  milk               0.003333    0.211864  3.223519
159                  milk               0.003333    0.238095  3.986501

[160 rows x 5 columns]

In [26]:
# ordenamos por mayor lift los primeros 5
resultDataFrame.nlargest(n = 5, columns = 'lift')

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                   izq   der   support  confidence      lift
126               soup  milk  0.003066    0.383333  7.987176
150               soup        0.003066    0.383333  7.987176
125  frozen vegetables  milk  0.003333    0.294118  6.128268
149  frozen vegetables        0.003333    0.294118  6.128268
108  whole wheat pasta        0.003866    0.402778  6.128268

In [27]:
# usemos apriori de mlxtend
# https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/#api

# primero hay que preprocesar y dejarlo en formato one-hot encoder
# Create an instace of our TransactionEncoder cabslass
te = TransactionEncoder()
# Fit and transform our dataset which is a list of lists into an array of True and False.
te_array = te.fit(transactions).transform(transactions)
te_array

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array([[False, False,  True, ...,  True, False, False],
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       ...,
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False,  True, False]])

In [28]:
te_array.shape

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(7501, 121)

In [29]:
# Convert this into a dataframe for better visualisation and for applying association rules onto the dataframe.

basket = pd.DataFrame(te_array,columns=te.columns_)

te.columns_

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

['',
 ' asparagus',
 'almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'ground beef',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'turkey',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini']

In [30]:
basket

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,True,True,False,True,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [31]:
# remove the first column as it does not contain any infomation
basket.drop(columns=[''],axis=1,inplace=True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [32]:
basket

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [33]:
# mlxtend apriori(df, min_support=0.5, use_colnames=False, max_len=None, verbose=0, low_memory=False)
# rules = apriori(transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2)
freq_items = mlx_apriori(basket, min_support=0.003, use_colnames=True)
freq_items

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

       support                                           itemsets
0     0.020397                                          (almonds)
1     0.008932                                (antioxydant juice)
2     0.004666                                        (asparagus)
3     0.033329                                          (avocado)
4     0.004533                                      (babies food)
...        ...                                                ...
1438  0.003066  (pancakes, spaghetti, mineral water, ground beef)
1439  0.003066  (spaghetti, mineral water, tomatoes, ground beef)
1440  0.003333        (milk, spaghetti, mineral water, olive oil)
1441  0.003066           (milk, shrimp, mineral water, spaghetti)
1442  0.003333         (milk, spaghetti, mineral water, tomatoes)

[1443 rows x 2 columns]

In [35]:
# https://github.com/rasbt/mlxtend/issues/980
# https://aldosari.medium.com/understanding-association-rule-mining-key-terms-and-metrics

rules_mlx = association_rules(freq_items, metric="confidence", min_threshold=0.2, num_itemsets=7)
rules_mlx

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(almonds),(burgers),0.020397,0.087188,0.005199,0.254902,2.923577,1.0,0.003421,1.225089,0.671653,0.050781,0.183733,0.157267
1,(almonds),(chocolate),0.020397,0.163845,0.005999,0.294118,1.795099,1.0,0.002657,1.184553,0.452150,0.033657,0.155800,0.165366
2,(almonds),(eggs),0.020397,0.179709,0.006532,0.320261,1.782108,1.0,0.002867,1.206774,0.448005,0.033747,0.171344,0.178306
3,(almonds),(french fries),0.020397,0.170911,0.004399,0.215686,1.261983,1.0,0.000913,1.057089,0.211919,0.023538,0.054006,0.120714
4,(almonds),(green tea),0.020397,0.132116,0.005066,0.248366,1.879913,1.0,0.002371,1.154663,0.477806,0.034358,0.133947,0.143356
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1357,"(milk, spaghetti, mineral water)",(tomatoes),0.015731,0.068391,0.003333,0.211864,3.097846,1.0,0.002257,1.182042,0.688018,0.041254,0.154006,0.130299
1358,"(milk, spaghetti, tomatoes)",(mineral water),0.005866,0.238368,0.003333,0.568182,2.383631,1.0,0.001935,1.763779,0.583897,0.013835,0.433036,0.291082
1359,"(milk, mineral water, tomatoes)",(spaghetti),0.006532,0.174110,0.003333,0.510204,2.930353,1.0,0.002196,1.686192,0.663076,0.018797,0.406948,0.264673
1360,"(spaghetti, mineral water, tomatoes)",(milk),0.009332,0.129583,0.003333,0.357143,2.756099,1.0,0.002124,1.353982,0.643171,0.024582,0.261438,0.191432
1361,"(milk, tomatoes)","(spaghetti, mineral water)",0.013998,0.059725,0.003333,0.238095,3.986501,1.0,0.002497,1.234110,0.759789,0.047348,0.189700,0.146949

In [36]:
type(rules_mlx)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

pandas.core.frame.DataFrame

In [37]:
result_mlx=rules_mlx.sort_values(by='lift',ascending=False)
result_mlx

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1319,"(soup, frozen vegetables)","(milk, mineral water)",0.007999,0.047994,0.003066,0.383333,7.987176,1.0,0.002682,1.543794,0.881853,0.057935,0.352245,0.223611
1313,"(frozen vegetables, olive oil)","(milk, mineral water)",0.011332,0.047994,0.003333,0.294118,6.128268,1.0,0.002789,1.348676,0.846413,0.059524,0.258532,0.181781
1159,"(whole wheat pasta, mineral water)",(olive oil),0.009599,0.065858,0.003866,0.402778,6.115863,1.0,0.003234,1.564145,0.844598,0.054004,0.360673,0.230741
1318,"(milk, soup)","(mineral water, frozen vegetables)",0.015198,0.035729,0.003066,0.201754,5.646864,1.0,0.002523,1.207988,0.835610,0.064067,0.172177,0.143788
1073,(tomato sauce),"(spaghetti, ground beef)",0.014131,0.039195,0.003066,0.216981,5.535971,1.0,0.002512,1.227052,0.831108,0.061008,0.185039,0.147606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,(light mayo),(mineral water),0.027196,0.238368,0.006266,0.230392,0.966539,1.0,-0.000217,0.989636,-0.034364,0.024165,-0.010472,0.128339
137,(escalope),(mineral water),0.079323,0.238368,0.017064,0.215126,0.902495,1.0,-0.001844,0.970387,-0.105024,0.056763,-0.030516,0.143357
844,"(green tea, french fries)",(mineral water),0.028530,0.238368,0.006133,0.214953,0.901770,1.0,-0.000668,0.970174,-0.100824,0.023517,-0.030743,0.120340
135,(energy drink),(mineral water),0.026663,0.238368,0.005599,0.210000,0.880990,1.0,-0.000756,0.964091,-0.121873,0.021583,-0.037247,0.116745
260,(yogurt cake),(mineral water),0.027330,0.238368,0.005599,0.204878,0.859502,1.0,-0.000915,0.957880,-0.143877,0.021527,-0.043972,0.114184