# Sistemas de Recomendación

In [40]:
import pandas as pd
import numpy as np

## Similitud coseno

$$sim(\pmb x, \pmb y) = \frac {\pmb x \cdot \pmb y}{||\pmb x|| \cdot ||\pmb y||}$$

¿Cómo calcularla en Python?

Supongamos que tenemos la siguiente matriz:

|  	| Libro A 	| Libro B 	| Libro C 	|
|-------	|---------	|---------	|---------	|
| Juan 	| 5 	| 4 	| 4 	|
| Diego 	| 4 	| 5 	| 5 	|


Podemos calcular la similitud coseno empleando sklearn:

In [41]:
from sklearn.metrics.pairwise import cosine_similarity
Juan = [5,4,4]
Diego = [4,5,5]
cosine_similarity([Juan, Diego])

array([[1.        , 0.97823198],
       [0.97823198, 1.        ]])

También podemos calcular la similitud a mano:

In [3]:
(5*4 + 4*5 + 4*5)/(np.sqrt(5**2+4**2+4**2)*np.sqrt(4**2+5**2+5**2))

0.9782319760890369

O empleando Numpy

Calcular la similitud coseno usando numpy (con np.dot y np.linalg.norm)

In [42]:
np.dot(Juan,Diego)/np.dot(np.linalg.norm(Juan), np.linalg.norm(Diego))

0.9782319760890369

Ahora bien, cuando tenemos una matriz user-item de la vida real, tenemos muchos casos faltantes. En esta situación, no podremos calcular la similitud coseno tan fácilmente...

In [43]:
user_item = np.array([[5, np.nan, 4],[4,3,5],[4,5,5],[np.nan, 5, np.nan], [np.nan, 5, 3]])
user_item

array([[ 5., nan,  4.],
       [ 4.,  3.,  5.],
       [ 4.,  5.,  5.],
       [nan,  5., nan],
       [nan,  5.,  3.]])

## Surprise

En esta notebook vamos a emplear la librería surprise. Esta es una librería que se basa en la API de scikit-learn y permite implementar varios algoritmos básicos de recomendación.

Comencemos cargando un dataset clásico en sistemas de recomendación: MovieLens (https://movielens.org/). Esta es una página de recomendación de películas que abrió información histórica.

In [44]:
!pip list

Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         1.1.1
aiohappyeyeballs                   2.4.4
aiohttp                            3.11.9
aiosignal                          1.3.1
alabaster                          1.0.0
albucore                           0.0.19
albumentations                     1.4.20
altair                             4.2.2
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.5.1
arviz                              0.20.0
astropy                            6.1.7
astropy-iers-data                  0.2024.12.2.0.35.34
astunparse                         1.6.3
async-timeout                      4.0.3
atpublic                           4.1.0
attrs                              24.2.0
audioread                          3.0.1
autograd                           1.7.0
babel                              2.16.0
backcall                           0.2.0
beautifulsoup4                     4.12.3
bigframes                          1.27.0
bigquery-magics                    0.4.0
bleach                             6.2.0
blinker                            1.9.0
blis                               0.7.11
blosc2                             2.7.1
bokeh                              3.6.1
Bottleneck                         1.4.2
bqplot                             0.12.43
branca                             0.8.0
CacheControl                       0.14.1
cachetools                         5.5.0
catalogue                          2.0.10
certifi                            2024.8.30
cffi                               1.17.1
chardet                            5.2.0
charset-normalizer                 3.4.0
chex                               0.1.87
clarabel                           0.9.0
click                              8.1.7
cloudpathlib                       0.20.0
cloudpickle                        3.1.0
cmake                              3.30.5
cmdstanpy                          1.2.4
colorcet                           3.1.0
colorlover                         0.3.0
colour                             0.1.5
community                          1.0.0b1
confection                         0.1.5
cons                               0.4.6
contourpy                          1.3.1
cryptography                       43.0.3
cuda-python                        12.2.1
cudf-cu12                          24.10.1
cufflinks                          0.17.3
cupy-cuda12x                       12.2.0
cvxopt                             1.3.2
cvxpy                              1.5.4
cycler                             0.12.1
cymem                              2.0.10
Cython                             3.0.11
dask                               2024.10.0
datascience                        0.17.6
db-dtypes                          1.3.1
dbus-python                        1.2.18
debugpy                            1.8.0
decorator                          4.4.2
defusedxml                         0.7.1
Deprecated                         1.2.15
diffusers                          0.31.0
distro                             1.9.0
dlib                               19.24.2
dm-tree                            0.1.8
docker-pycreds                     0.4.0
docstring_parser                   0.16
docutils                           0.21.2
dopamine_rl                        4.0.9
duckdb                             1.1.3
earthengine-api                    1.2.0
easydict                           1.13
ecos                               2.0.14
editdistance                       0.8.1
eerepr                             0.0.4
einops                             0.8.0
en-core-web-sm                     3.7.1
entrypoints                        0.4
et_xmlfile                         2.0.0
etils                              1.11.0
etuples                            0.3.9
eval_type_backport                 0.2.0
exceptiongroup                     1.2.2
fastai                             2.7.18
fastcore                           1.7.22
fastdownload                       0.0.7
fastjsonschema                     2.21.1
fastprogress                       1.0.3
fastrlock                          0.8.2
filelock                           3.16.1
firebase-admin                     6.5.0
Flask                              3.0.3
flatbuffers                        24.3.25
flax                               0.8.5
folium                             0.18.0
fonttools                          4.55.0
frozendict                         2.4.6
frozenlist                         1.5.0
fsspec                             2024.10.0
future                             1.0.0
gast                               0.6.0
gcsfs                              2024.10.0
GDAL                               3.6.4
gdown                              5.2.0
geemap                             0.35.1
gensim                             4.3.3
geocoder                           1.38.1
geographiclib                      2.0
geopandas                          1.0.1
geopy                              2.4.1
gin-config                         0.5.0
gitdb                              4.0.11
GitPython                          3.1.43
glob2                              0.7
google                             2.0.3
google-ai-generativelanguage       0.6.10
google-api-core                    2.19.2
google-api-python-client           2.151.0
google-auth                        2.27.0
google-auth-httplib2               0.2.0
google-auth-oauthlib               1.2.1
google-cloud-aiplatform            1.71.1
google-cloud-bigquery              3.25.0
google-cloud-bigquery-connection   1.16.1
google-cloud-bigquery-storage      2.27.0
google-cloud-bigtable              2.27.0
google-cloud-core                  2.4.1
google-cloud-datastore             2.20.1
google-cloud-firestore             2.19.0
google-cloud-functions             1.18.1
google-cloud-iam                   2.16.1
google-cloud-language              2.15.1
google-cloud-pubsub                2.27.1
google-cloud-resource-manager      1.13.1
google-cloud-storage               2.8.0
google-cloud-translate             3.17.0
google-colab                       1.0.0
google-crc32c                      1.6.0
google-generativeai                0.8.3
google-pasta                       0.2.0
google-resumable-media             2.7.2
googleapis-common-protos           1.66.0
googledrivedownloader              0.4
graphviz                           0.20.3
greenlet                           3.1.1
grpc-google-iam-v1                 0.13.1
grpcio                             1.68.1
grpcio-status                      1.62.3
gspread                            6.0.2
gspread-dataframe                  3.3.1
gym                                0.25.2
gym-notices                        0.0.8
h11                                0.14.0
h5netcdf                           1.4.1
h5py                               3.12.1
holidays                           0.62
holoviews                          1.20.0
html5lib                           1.1
httpcore                           1.0.7
httpimport                         1.4.0
httplib2                           0.22.0
httpx                              0.28.0
huggingface-hub                    0.26.3
humanize                           4.11.0
hyperopt                           0.2.7
ibis-framework                     9.2.0
idna                               3.10
imageio                            2.36.1
imageio-ffmpeg                     0.5.1
imagesize                          1.4.1
imbalanced-learn                   0.12.4
imgaug                             0.4.0
immutabledict                      4.2.1
importlib_metadata                 8.5.0
importlib_resources                6.4.5
imutils                            0.5.4
inflect                            7.4.0
iniconfig                          2.0.0
intel-cmplr-lib-ur                 2025.0.3
intel-openmp                       2025.0.3
ipyevents                          2.0.2
ipyfilechooser                     0.6.0
ipykernel                          5.5.6
ipyleaflet                         0.19.2
ipyparallel                        8.8.0
ipython                            7.34.0
ipython-genutils                   0.2.0
ipython-sql                        0.5.0
ipytree                            0.2.2
ipywidgets                         7.7.1
itsdangerous                       2.2.0
jax                                0.4.33
jax-cuda12-pjrt                    0.4.33
jax-cuda12-plugin                  0.4.33
jaxlib                             0.4.33
jeepney                            0.7.1
jellyfish                          1.1.0
jieba                              0.42.1
Jinja2                             3.1.4
jiter                              0.8.0
joblib                             1.4.2
jsonpatch                          1.33
jsonpickle                         4.0.0
jsonpointer                        3.0.0
jsonschema                         4.23.0
jsonschema-specifications          2024.10.1
jupyter-client                     6.1.12
jupyter-console                    6.1.0
jupyter_core                       5.7.2
jupyter-leaflet                    0.19.2
jupyter-server                     1.24.0
jupyterlab_pygments                0.3.0
jupyterlab_widgets                 3.0.13
kaggle                             1.6.17
kagglehub                          0.3.4
keras                              3.5.0
keyring                            23.5.0
kiwisolver                         1.4.7
langchain                          0.3.9
langchain-core                     0.3.21
langchain-text-splitters           0.3.2
langcodes                          3.5.0
langsmith                          0.1.147
language_data                      1.3.0
launchpadlib                       1.10.16
lazr.restfulclient                 0.14.4
lazr.uri                           1.0.6
lazy_loader                        0.4
libclang                           18.1.1
libcudf-cu12                       24.10.1
librosa                            0.10.2.post1
lightgbm                           4.5.0
linkify-it-py                      2.0.3
llvmlite                           0.43.0
locket                             1.0.0
logical-unification                0.4.6
lxml                               5.3.0
marisa-trie                        1.2.1
Markdown                           3.7
markdown-it-py                     3.0.0
MarkupSafe                         3.0.2
matplotlib                         3.8.0
matplotlib-inline                  0.1.7
matplotlib-venn                    1.1.1
mdit-py-plugins                    0.4.2
mdurl                              0.1.2
miniKanren                         1.0.3
missingno                          0.5.2
mistune                            3.0.2
mizani                             0.13.0
mkl                                2025.0.1
ml-dtypes                          0.4.1
mlxtend                            0.23.3
more-itertools                     10.5.0
moviepy                            1.0.3
mpmath                             1.3.0
msgpack                            1.1.0
multidict                          6.1.0
multipledispatch                   1.0.0
multitasking                       0.0.11
murmurhash                         1.0.11
music21                            9.3.0
namex                              0.0.8
natsort                            8.4.0
nbclassic                          1.1.0
nbclient                           0.10.1
nbconvert                          7.16.4
nbformat                           5.10.4
ndindex                            1.9.2
nest-asyncio                       1.6.0
networkx                           3.4.2
nibabel                            5.3.2
nltk                               3.9.1
notebook                           6.5.5
notebook_shim                      0.2.4
numba                              0.60.0
numexpr                            2.10.2
numpy                              1.26.4
nvidia-cublas-cu12                 12.6.4.1
nvidia-cuda-cupti-cu12             12.6.80
nvidia-cuda-nvcc-cu12              12.6.85
nvidia-cuda-runtime-cu12           12.6.77
nvidia-cudnn-cu12                  9.5.1.17
nvidia-cufft-cu12                  11.3.0.4
nvidia-curand-cu12                 10.3.7.77
nvidia-cusolver-cu12               11.7.1.2
nvidia-cusparse-cu12               12.5.4.2
nvidia-nccl-cu12                   2.23.4
nvidia-nvjitlink-cu12              12.6.85
nvtx                               0.2.10
nx-cugraph-cu12                    24.10.0
oauth2client                       4.1.3
oauthlib                           3.2.2
openai                             1.54.5
opencv-contrib-python              4.10.0.84
opencv-python                      4.10.0.84
opencv-python-headless             4.10.0.84
openpyxl                           3.1.5
opentelemetry-api                  1.28.2
opentelemetry-sdk                  1.28.2
opentelemetry-semantic-conventions 0.49b2
opt_einsum                         3.4.0
optax                              0.2.4
optree                             0.13.1
orbax-checkpoint                   0.6.4
orjson                             3.10.12
osqp                               0.6.7.post3
packaging                          24.2
pandas                             2.2.2
pandas-datareader                  0.10.0
pandas-gbq                         0.24.0
pandas-stubs                       2.2.2.240909
pandocfilters                      1.5.1
panel                              1.5.4
param                              2.1.1
parso                              0.8.4
parsy                              2.1
partd                              1.4.2
pathlib                            1.0.1
patsy                              1.0.1
peewee                             3.17.8
peft                               0.13.2
pexpect                            4.9.0
pickleshare                        0.7.5
pillow                             11.0.0
pip                                24.1.2
platformdirs                       4.3.6
plotly                             5.24.1
plotnine                           0.14.3
pluggy                             1.5.0
ply                                3.11
polars                             1.9.0
pooch                              1.8.2
portpicker                         1.5.2
preshed                            3.0.9
prettytable                        3.12.0
proglog                            0.1.10
progressbar2                       4.5.0
prometheus_client                  0.21.0
promise                            2.3
prompt_toolkit                     3.0.48
propcache                          0.2.1
prophet                            1.1.6
proto-plus                         1.25.0
protobuf                           4.25.5
psutil                             5.9.5
psycopg2                           2.9.10
ptyprocess                         0.7.0
py-cpuinfo                         9.0.0
py4j                               0.10.9.7
pyarrow                            17.0.0
pyarrow-hotfix                     0.6
pyasn1                             0.6.1
pyasn1_modules                     0.4.1
pycocotools                        2.0.8
pycparser                          2.22
pydantic                           2.10.2
pydantic_core                      2.27.1
pydata-google-auth                 1.9.0
pydot                              3.0.3
pydotplus                          2.0.2
PyDrive                            1.3.1
PyDrive2                           1.21.3
pyerfa                             2.0.1.5
pygame                             2.6.1
pygit2                             1.16.0
Pygments                           2.18.0
PyGObject                          3.42.1
PyJWT                              2.10.1
pylibcudf-cu12                     24.10.1
pylibcugraph-cu12                  24.10.0
pylibraft-cu12                     24.10.0
pymc                               5.18.2
pymystem3                          0.2.0
pynvjitlink-cu12                   0.4.0
pyogrio                            0.10.0
Pyomo                              6.8.2
PyOpenGL                           3.1.7
pyOpenSSL                          24.2.1
pyparsing                          3.2.0
pyperclip                          1.9.0
pyproj                             3.7.0
pyshp                              2.3.1
PySocks                            1.7.1
pyspark                            3.5.3
pytensor                           2.26.3
pytest                             8.3.4
python-apt                         0.0.0
python-box                         7.2.0
python-dateutil                    2.8.2
python-louvain                     0.16
python-slugify                     8.0.4
python-utils                       3.9.1
pytz                               2024.2
pyviz_comms                        3.0.3
PyYAML                             6.0.2
pyzmq                              24.0.1
qdldl                              0.1.7.post4
ratelim                            0.1.6
referencing                        0.35.1
regex                              2024.9.11
requests                           2.32.3
requests-oauthlib                  1.3.1
requests-toolbelt                  1.0.0
requirements-parser                0.9.0
rich                               13.9.4
rmm-cu12                           24.10.0
rpds-py                            0.22.0
rpy2                               3.4.2
rsa                                4.9
safetensors                        0.4.5
scikit-image                       0.24.0
scikit-learn                       1.5.2
scikit-surprise                    1.1.4
scipy                              1.13.1
scooby                             0.10.0
scs                                3.2.7
seaborn                            0.13.2
SecretStorage                      3.3.1
Send2Trash                         1.8.3
sentence-transformers              3.2.1
sentencepiece                      0.2.0
sentry-sdk                         2.19.0
setproctitle                       1.3.4
setuptools                         75.1.0
shap                               0.46.0
shapely                            2.0.6
shellingham                        1.5.4
simple-parsing                     0.1.6
six                                1.16.0
sklearn-pandas                     2.2.0
slicer                             0.0.8
smart-open                         7.0.5
smmap                              5.0.1
sniffio                            1.3.1
snowballstemmer                    2.2.0
soundfile                          0.12.1
soupsieve                          2.6
soxr                               0.5.0.post1
spacy                              3.7.5
spacy-legacy                       3.0.12
spacy-loggers                      1.0.5
Sphinx                             8.1.3
sphinxcontrib-applehelp            2.0.0
sphinxcontrib-devhelp              2.0.0
sphinxcontrib-htmlhelp             2.1.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               2.0.0
sphinxcontrib-serializinghtml      2.0.0
SQLAlchemy                         2.0.36
sqlglot                            25.1.0
sqlparse                           0.5.2
srsly                              2.4.8
stanio                             0.5.1
statsmodels                        0.14.4
StrEnum                            0.4.15
stringzilla                        3.11.0
surprise                           0.1
sympy                              1.13.1
tables                             3.10.1
tabulate                           0.9.0
tbb                                2022.0.0
tcmlib                             1.2.0
tenacity                           9.0.0

In [6]:
!pip install surprise
# https://surprise.readthedocs.io/

Collecting surprise
  Downloading surprise-0.1-py2.py3-none-any.whl.metadata (327 bytes)
Collecting scikit-surprise (from surprise)
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.13.1)
Downloading surprise-0.1-py2.py3-none-any.whl (1.8 kB)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp310-cp310-linux_x86_64.whl size=2357273 sha256=92089159ef7d81eb56c12f6b0c5b12cad27fa1175078ebc3e138d4979c7ac006
  Stored in directory: /root/.cache/pip/wheels/4b/3f/df/6acbf0a40397d9bf3ff97f582cc22fb9ce66adde75bc71fd54
Successfully built scikit-surprise
Installing collected packages: scikit-surprise, surprise
Successfully installed scikit-surprise-1.1.4 surprise-0.1

In [ ]:
# Bajamos el dataset. En windows pueden descargarlo entrando al link manualmente
#!wget https://files.grouplens.org/datasets/movielens/ml-100k/u.data

In [51]:
# información sobre Movie lens https://files.grouplens.org/datasets/movielens/ml-100k-README.txt

mlens = pd.read_csv("https://files.grouplens.org/datasets/movielens/ml-100k/u.data",sep="\t",header=None)
mlens.columns = ["user_id","item_id","rating","timestamp"]
mlens

       user_id  item_id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [47]:
len(mlens['user_id'].unique())

943

In [48]:
len(mlens['item_id'].unique())

1682

In [52]:
mlens.drop("timestamp", axis=1, inplace=True)

In [53]:
mlens

       user_id  item_id  rating
0          196      242       3
1          186      302       3
2           22      377       1
3          244       51       2
4          166      346       1
...        ...      ...     ...
99995      880      476       3
99996      716      204       5
99997      276     1090       1
99998       13      225       2
99999       12      203       3

[100000 rows x 3 columns]

El paquete surprise no recibe directamente un objeto DataFrame.
Para parsear y leer un conjunto de datos debe hacerlo a través de dos nuevos objetos: Reader y Dataset.
En Reader debemos especificar el valor mínimo y el valor máximo de los ratings.
Dataset nos permite leer datos desde distintas fuentes.

In [54]:
from surprise import Dataset, Reader
reader = Reader(rating_scale=(mlens["rating"].min(),mlens["rating"].max()))

In [55]:
dataset = Dataset.load_from_df(mlens,reader)
dataset

Ahora cargue SVD y GridSearchCV, ambos de surprise.

In [56]:
from surprise import SVD
from surprise.model_selection.search import GridSearchCV
'''
classsurprise.prediction_algorithms.matrix_factorization.SVD(n_factors=100,
n_epochs=20, biased=True, init_mean=0, init_std_dev=0.1, lr_all=0.005, reg_all=0.02,
lr_bu=None, lr_bi=None, lr_pu=None, lr_qi=None, reg_bu=None, reg_bi=None,
reg_pu=None, reg_qi=None, random_state=None, verbose=False)

class surprise.model_selection.search.GridSearchCV(algo_class, param_grid,
measures=['rmse', 'mae'], cv=None, refit=False, return_train_measures=False,
n_jobs=1, pre_dispatch='2*n_jobs', joblib_verbose=0)
'''

"\nclasssurprise.prediction_algorithms.matrix_factorization.SVD(n_factors=100,\nn_epochs=20, biased=True, init_mean=0, init_std_dev=0.1, lr_all=0.005, reg_all=0.02,\nlr_bu=None, lr_bi=None, lr_pu=None, lr_qi=None, reg_bu=None, reg_bi=None,\nreg_pu=None, reg_qi=None, random_state=None, verbose=False)\n\nclass surprise.model_selection.search.GridSearchCV(algo_class, param_grid,\nmeasures=['rmse', 'mae'], cv=None, refit=False, return_train_measures=False,\nn_jobs=1, pre_dispatch='2*n_jobs', joblib_verbose=0)\n"

Genere una grilla de parámetros donde se prueben distintas combinaciones de:  
  - epochs: es la cantidad de pasadas sobre el dataset que hará el algoritmo empleando descenso por el gradiente  
  - biased: usar parámetros de sesgo o no  
  - lr_all: learning rate para todos los parámetros  
  - reg_all: término de regularización para todos los parámetros (lambda)

In [57]:
param_grid = {'n_epochs': [5, 10], 'lr_all': [0.002, 0.005], 'reg_all': [0.4, 0.6]}

Emplee GridSearchCV, SVD y el diccionario con los parámetros para probar, y entrene un modelo. Note que a GridSearchCV necesita pasarle un modelo sin instanciar. Además, setee el parámetro refit a True y con measures = ["rmse","fcp"]

In [58]:
gs = GridSearchCV(SVD, param_grid, measures=['fcp',"rmse"], cv=3, refit=True)

In [59]:
gs.fit(dataset)

Imprima el rmse y el fcp, y la mejor combinación de parámetros

In [60]:
gs.best_score

{'fcp': 0.6985552121591029, 'rmse': 0.963533832255186}

In [61]:
gs.best_params

{'fcp': {'n_epochs': 10, 'lr_all': 0.005, 'reg_all': 0.4},
 'rmse': {'n_epochs': 10, 'lr_all': 0.005, 'reg_all': 0.4}}

Guarde el modelo con mayor fcp y prediga el rating para el user id 196 e item id 242

In [62]:
best_model = gs.best_estimator["fcp"]

In [19]:
pred = best_model.predict("196", "242")
pred

Prediction(uid='196', iid='242', r_ui=None, est=3.52986, details={'was_impossible': False})

In [20]:
pred.est

3.52986

Pruebe empleando otros modelos como SVDpp,  NMF,  KNNWithZScore e intente superar el valor obtenido

In [63]:
from surprise import SVDpp

'''
class surprise.prediction_algorithms.matrix_factorization.SVDpp(n_factors=20, n_epochs=20,
init_mean=0, init_std_dev=0.1, lr_all=0.007, reg_all=0.02, lr_bu=None, lr_bi=None,
lr_pu=None, lr_qi=None, lr_yj=None, reg_bu=None, reg_bi=None, reg_pu=None, reg_qi=None,
reg_yj=None, random_state=None, verbose=False, cache_ratings=False)
'''

gs1 = GridSearchCV(SVDpp, param_grid, measures=['fcp',"rmse"], cv=3, refit=True)
gs1.fit(dataset)
gs1.best_score

{'fcp': 0.6972050862116247, 'rmse': 0.9646864118401878}

In [22]:
from surprise import NMF

'''
class surprise.prediction_algorithms.matrix_factorization.NMF(n_factors=15, n_epochs=50,
biased=False, reg_pu=0.06, reg_qi=0.06, reg_bu=0.02, reg_bi=0.02, lr_bu=0.005,
lr_bi=0.005, init_low=0, init_high=1, random_state=None, verbose=False)
'''

param_grid2 = {'n_epochs': [5, 10], 'lr_bu': [0.002, 0.005], 'lr_bi': [0.002, 0.005],
               'reg_pu': [0.04, 0.06],'reg_qi': [0.04, 0.06],'reg_bu': [0.01, 0.03],'reg_bi': [0.01, 0.03]}

gs2 = GridSearchCV(NMF, param_grid2, measures=['fcp',"rmse"], cv=3, refit=True)
gs2.fit(dataset)
gs2.best_score

{'fcp': 0.6818098677673348, 'rmse': 0.997309772843237}

In [23]:
from surprise import KNNWithZScore

'''
classsurprise.prediction_algorithms.knns.KNNWithZScore(k=40, min_k=1,
sim_options={}, verbose=True, **kwargs)
'''
param_grid3={'k': range(20, 65,5)}
gs3 = GridSearchCV(KNNWithZScore, param_grid3, measures=['fcp',"rmse"], cv=3, refit=True)
gs3.fit(dataset)
gs3.best_score

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.

{'fcp': 0.7060784337366138, 'rmse': 0.9558445998537705}

# Recomendación basada en el contenido

En este ejemplo vamos a tomar un corpus de textos de autores latinoamericanos para sugerir uno similar a uno dado. Para esto construiremos una matriz TFIDF, de frecuencias normalizadas de términos por documento, y usaremos la similitud coseno para medir distancias entre los distintos textos.

In [64]:
!git clone https://github.com/karen-pal/borges

fatal: destination path 'borges' already exists and is not an empty directory.

In [65]:
!ls

borges	sample_data

In [67]:
!cd borges
!ls borges/

borges.ipynb  full_text_scrapper.py  link_scrapper.py  scraper.py		  uso_simple.ipynb
datasets      LDA.ipynb		     README.md	       sentence_similarity.ipynb

In [68]:
!ls borges/datasets

borges_sentiment_corpus.csv  datasets_csv  datasets_pkl  full_corpus.csv  links  pkl_to_csv.ipynb

In [69]:
import pickle
from pathlib import Path
import pandas as pd

df = pd.DataFrame()
# usando el asterisco de "wildcard" traemos todos los archivos en formato pickle
pkls = Path('.').glob('./borges/datasets/datasets_pkl/*texts.pkl')

# leemos todos los pickles y concatenarlos en un DataFrame
for pkl in pkls:
    with open(pkl, 'rb') as inp:
        df_ = pickle.load(inp)
    df = pd.concat([df, df_])

df.shape

(719, 3)

In [70]:
df

,link,text_metadata,text
0,https://ciudadseva.com/texto/el-alma/,"{'title': 'El alma', 'metadata': '[Cuento - Te...",I ¿Qué viene a buscar el Diablo en mi aposento...
1,https://ciudadseva.com/texto/el-difunto-y-yo/,"{'title': 'El difunto y yo', 'metadata': '[Cue...",Examiné apresuradamente la extraña situación e...
2,https://ciudadseva.com/texto/el-pequeno-nazareno/,"{'title': 'El pequeño nazareno', 'metadata': '...","El miércoles santo, el pequeño Nazareno de tún..."
3,https://ciudadseva.com/texto/la-tienda-de-mune...,"{'title': 'La tienda de muñecos', 'metadata': ...","No sé cuándo, dónde ni por quién fue escrito e..."
0,https://ciudadseva.com/texto/el-crepusculo-del...,"{'title': 'El crepúsculo del diablo', 'metadat...",En el borde de una pila que muestra su cuenca ...
...,...,...,...
20,https://ciudadseva.com/texto/tempestad-de-almas/,"{'title': 'Tempestad de almas', 'metadata': '[...","Ah, si lo hubiera sabido, no nacía, ah, si lo ..."
21,https://ciudadseva.com/texto/un-caso-complicado/,"{'title': 'Un caso complicado', 'metadata': '[...","Pues sí. Cuyo padre era amante, con un alfiler..."
22,https://ciudadseva.com/texto/una-gallina/,"{'title': 'Una gallina', 'metadata': '[Cuento ...",Era una gallina de domingo. Todavía vivía porq...
23,https://ciudadseva.com/texto/una-tarde-plena/,"{'title': 'Una tarde plena', 'metadata': '[Cue...","El saguino¹ es tan pequeño como un ratón, y de..."
24,https://ciudadseva.com/texto/vida-al-natural/,"{'title': 'Vida al natural', 'metadata': '[Min...",Pues en el río había algo como el fuego del ho...

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

WARNING:root:Quickchart encountered unexpected dtypes in columns: "(['text_metadata'],)"

No charts were generated by quickchart

In [72]:
df['text_metadata'].sample(2)

19    {'title': 'La mano pegada', 'metadata': '[Cuen...
6     {'title': 'El rey burgués', 'metadata': '[Cuen...
Name: text_metadata, dtype: object

In [73]:
df.columns

Index(['link', 'text_metadata', 'text'], dtype='object')

In [74]:
# separamos de la metadata el título y autor en sus propias columnas
df['title'] = df['text_metadata'].apply(lambda x: x['title'])
df['author'] = df['text_metadata'].apply(lambda x: x['author'])

In [75]:
# vemos los autores disponibloes
df['author'].value_counts()

author
Jorge Luis Borges             60
Julio Cortázar                55
Baldomero Lillo               50
Augusto Monterroso            45
Juan José Arreola             45
Alfonso Reyes                 37
Enrique Anderson Imbert       36
Mario Benedetti               33
Julio Ramón Ribeyro           27
Roberto Arlt                  25
Clarice Lispector             25
Julio Torri                   23
Felisberto Hernández          15
Luis Vidales                  14
Rubén Darío                   13
Adolfo Bioy Casares           13
Álvaro Mutis                  11
Juan Rulfo                    10
Edmundo Valadés               10
Juan Rodolfo Wilcock          10
Manuel A. Alonso               9
Elena Garro                    9
Salarrué                       9
Alejo Carpentier               8
Eduardo Gudiño Kieffer         8
Juan Bosch                     8
Silvina Ocampo                 7
Virgilio Díaz Grullón          7
Andrés Rivera                  7
Rodolfo Walsh                  6
Ricardo Güiraldes              6
Pablo Palacio                  5
Manuel Romero de Terreros      5
José Donoso                    5
Julio Garmendia                4
[Cuento - Texto completo.]     4
Gregorio López y Fuentes       4
Vicente Huidobro               3
José Lezama Lima               3
Amparo Dávila                  3
Octavio Paz                    3
Macedonio Fernández            3
Rómulo Gallegos                3
José María Arguedas            3
Inés Arredondo                 3
María Luisa Bombal             3
Virgilio Piñera                3
Rubén Bareiro Saguier          3
José Edwards                   3
Sergio Pitol                   3
Teresa de la Parra             2
Santiago Dabove                2
Leonora Carrington             2
Humberto Arenal                2
Esteban Echeverría             1
Ricardo Jaimes Freyre          1
Manuel González Zeledón        1
Carmen Lyra                    1
Name: count, dtype: int64

In [76]:
# quitamos duplicados y reiniciamos el índice
df = df.drop_duplicates(subset=[c for c in df.columns if c != 'text_metadata'])
df = df.reset_index(drop=True)
df.shape

(693, 5)

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel
from pprint import pprint

Vamos a calcular las matrices de ocurrencias de términos usando sklearn.

Ámbas clases primero construyen el vocabulario total, y luego:  
- **CountVectorizer** nos devuelve la frecuencia absoluta de cada término por cada documento.
- [**TF-IDF**](https://en.wikipedia.org/wiki/Tf%E2%80%93idf): calcula la frecuencia de cada término por documento, y normaliza por el total de documentos donde el término aparece.

$${tf} (t,d)={\frac {f_{t,d}}{\sum _{t'\in d}{f_{t',d}}}}$$

$$
idf( t, D ) = log \frac{ \text{| } D \text{ |} }{ 1 + \text{| } \{ d \in D : t \in d \} \text{ |} }
$$


$$ tfidf( t, d, D ) = tf( t, d ) \times idf( t, D )
$$

In [78]:
# Instanciamos el CV
vectorizer = CountVectorizer()

doc1 = 'la matriz de frecuencias por palabras otorga información del contenido de un documento'
doc2 = 'las palabras que aparecen en un documento se relaciona con su tema'
# Definimos una lista con todos los strings
data_corpus = [doc1, doc2]

# Fiteamos el CV y transformamos los datos
X = vectorizer.fit_transform(data_corpus)

# Pasamos de sparse matrix a array usando .toarray()

print(X.toarray())
# Usando el metodo .get_feature_names() del CV podemos acceder al indice de palabras
print(vectorizer.get_feature_names_out())

[[0 0 1 2 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1]
 [1 1 0 0 0 1 1 0 0 0 1 0 0 1 0 1 1 1 1 1 1]]
['aparecen' 'con' 'contenido' 'de' 'del' 'documento' 'en' 'frecuencias'
 'información' 'la' 'las' 'matriz' 'otorga' 'palabras' 'por' 'que'
 'relaciona' 'se' 'su' 'tema' 'un']

In [79]:
X

<2x21 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [80]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop = list(stopwords.words('spanish'))
# eliminamos las "stop words", palabras comunes no informativas
tf = TfidfVectorizer(stop_words=stop)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [81]:
# calculamos los features para cada ítem (texto)
tfidf_matrix = tf.fit_transform(df['text'])

In [87]:
tfidf_matrix.shape

(693, 56608)

In [83]:
# calculamos las similitudes entre todos los documentos
cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)
n = 6

# diccionario creado para guardar el resultado en un formato (autor - titulo : puntaje, titulo, autor)
results = {}
for idx, row in df.iterrows():
    # guardamos los indices similares basados en la similitud coseno. Los ordenamos en modo ascendente, siendo 0 nada de similitud y 1 total
    similar_indices = cosine_similarities[idx].argsort()[:-n-2:-1]
    # guardamos los N más cercanos
    similar_items = [(f"{df['author'][i]} - {df['title'][i]}", round(cosine_similarities[idx][i], 3)) for i in similar_indices]
    results[f"{row['author']} - {row['title']}"] = similar_items[1:]

In [84]:
pprint(results['Jorge Luis Borges - El Aleph'])

[('Jorge Luis Borges - La escritura del dios', 0.144),
 ('Jorge Luis Borges - El inmortal', 0.135),
 ('Jorge Luis Borges - Utopía de un hombre que está cansado', 0.125),
 ('Felisberto Hernández - El acomodador', 0.122),
 ('Clarice Lispector - La búsqueda de la dignidad', 0.121),
 ('Jorge Luis Borges - Funes el memorioso', 0.11)]

In [85]:
def recomendar(autor, titulo):
    pprint(results[f"{autor} - {titulo}"])

In [86]:
recomendar('Julio Cortázar', 'Axolotl')

[('Felisberto Hernández - El acomodador', 0.134),
 ('Felisberto Hernández - El cocodrilo', 0.101),
 ('Felisberto Hernández - Menos Julia', 0.089),
 ('Julio Cortázar - Después del almuerzo', 0.088),
 ('Julio Cortázar - La noche boca arriba', 0.086),
 ('Julio Cortázar - La señorita Cora', 0.086)]

In [ ]:
# https://medium.com/@eng.saavedra/sistemas-de-recomendaci%C3%B3n-parte-2-b8a5dc9dc730
# https://towardsdatascience.com/item-based-collaborative-filtering-in-python-91f747200fab
# https://www.genbeta.com/web/asi-funcionan-las-recomendaciones-de-amazon