# Sistemas de Recomendación

In [1]:
import pandas as pd
import numpy as np

## Similitud coseno

$$sim(\pmb x, \pmb y) = \frac {\pmb x \cdot \pmb y}{||\pmb x|| \cdot ||\pmb y||}$$

¿Cómo calcularla en Python?

Supongamos que tenemos la siguiente matriz:

|  	| Libro A 	| Libro B 	| Libro C 	|
|-------	|---------	|---------	|---------	|
| Juan 	| 5 	| 4 	| 4 	|
| Diego 	| 4 	| 5 	| 5 	|


Podemos calcular la similitud coseno empleando sklearn:

In [2]:
from sklearn.metrics.pairwise import cosine_similarity
Juan = [5,4,4]
Diego = [4,5,5]
cosine_similarity([Juan, Diego])

array([[1.        , 0.97823198],
       [0.97823198, 1.        ]])

También podemos calcular la similitud a mano:

In [3]:
(5*4 + 4*5 + 4*5)/(np.sqrt(5**2+4**2+4**2)*np.sqrt(4**2+5**2+5**2))

0.9782319760890369

O empleando Numpy

Calcular la similitud coseno usando numpy (con np.dot y np.linalg.norm)

In [4]:
np.dot(Juan,Diego)/np.dot(np.linalg.norm(Juan), np.linalg.norm(Diego))

0.9782319760890369

Ahora bien, cuando tenemos una matriz user-item de la vida real, tenemos muchos casos faltantes. En esta situación, no podremos calcular la similitud coseno tan fácilmente...

In [5]:
user_item = np.array([[5, np.nan, 4],[4,3,5],[4,5,5],[np.nan, 5, np.nan], [np.nan, 5, 3]])
user_item

array([[ 5., nan,  4.],
       [ 4.,  3.,  5.],
       [ 4.,  5.,  5.],
       [nan,  5., nan],
       [nan,  5.,  3.]])

## Surprise

En esta notebook vamos a emplear la librería surprise. Esta es una librería que se basa en la API de scikit-learn y permite implementar varios algoritmos básicos de recomendación.

Comencemos cargando un dataset clásico en sistemas de recomendación: MovieLens (https://movielens.org/). Esta es una página de recomendación de películas que abrió información histórica.

In [6]:
!pip list

Package                           Version
--------------------------------- ------------------
adagio                            0.2.6
aext-assistant                    4.20.0
aext-assistant-server             4.20.0
aext-core                         4.20.0
aext-core-server                  4.20.0
aext_environments_server          4.20.0
aext-panels                       4.20.0
aext-panels-server                4.20.0
aext-project-filebrowser-server   4.20.0
aext-share-notebook               4.20.0
aext-share-notebook-server        4.20.0
aext-shared                       4.20.0
aext-toolbox                      4.20.0
affine                            2.4.0
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
alembic                           1.13.3
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-auth                     0.8.6
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.5.2
anaconda-client                   1.13.0
anaconda-navigator                2.6.3
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
applaunchservices                 0.3.0
appnope                           0.1.3
appscript                         1.2.5
apptools                          5.3.1
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
arviz                             0.22.0
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data                 0.2024.9.2.0.33.23
asttokens                         2.0.5
async-lru                         2.0.4
atomicwrites                      1.4.0
attrs                             23.1.0
Automat                           20.2.0
autopep8                          2.0.4
Babel                             2.11.0
bambi                             0.15.0
bcrypt                            3.2.0
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
black                             24.8.0
bleach                            4.1.0
blinker                           1.6.2
bokeh                             3.6.0
boltons                           23.0.0
botocore                          1.34.69
Bottleneck                        1.3.7
Brotli                            1.0.9
cachetools                        5.3.3
catboost                          1.2.8
certifi                           2025.4.26
cffi                              1.17.1
chardet                           4.0.0
charset-normalizer                3.3.2
click                             8.1.7
click-plugins                     1.1.1.2
cligj                             0.7.2
cloudpickle                       3.0.0
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.1
conda                             24.11.3
conda-build                       24.9.0
conda-content-trust               0.2.0
conda_index                       0.5.0
conda-libmamba-solver             24.9.0
conda-pack                        0.7.1
conda-package-handling            2.3.0
conda_package_streaming           0.10.0
conda-repo-cli                    1.0.114
conda-token                       0.6.0
configobj                         5.0.9
cons                              0.4.7
constantly                        23.10.4
contourpy                         1.2.0
cookiecutter                      2.6.0
coreforecast                      0.0.16
cryptography                      43.0.0
cssselect                         1.2.0
cycler                            0.11.0
cytoolz                           0.12.2
dacite                            1.9.2
darts                             0.37.1
dask                              2024.8.2
dask-expr                         1.1.13
datashader                        0.16.3
debugpy                           1.6.7
decorator                         5.1.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.3.8
distributed                       2024.8.2
distro                            1.9.0
dmglib                            0.9.5
docstring-to-markdown             0.11
docutils                          0.18.1
envisage                          7.0.4
et-xmlfile                        1.1.0
etuples                           0.3.10
executing                         0.8.3
fastjsonschema                    2.16.2
filelock                          3.19.1
flake8                            7.0.0
Flask                             3.0.3
fonttools                         4.51.0
formulae                          0.5.4
fqdn                              1.5.1
frozendict                        2.4.2
frozenlist                        1.4.0
fs                                2.4.16
fsspec                            2024.6.1
fugue                             0.9.1
gensim                            4.3.3
gitdb                             4.0.7
GitPython                         3.1.43
google                            3.0.0
graphviz                          0.21
greenlet                          3.0.1
h11                               0.14.0
h5netcdf                          1.6.4
h5py                              3.11.0
HeapDict                          1.0.1
holidays                          0.81
holoviews                         1.19.1
htmlmin                           0.1.12
httpcore                          1.0.2
httpx                             0.27.0
hvplot                            0.11.0
hyperlink                         21.0.0
idna                              3.7
imagecodecs                       2023.1.23
ImageHash                         4.3.1
imageio                           2.33.1
imagesize                         1.4.1
imbalanced-learn                  0.12.3
importlib-metadata                7.0.1
importlib_resources               6.5.2
incremental                       22.10.0
inflection                        0.5.1
iniconfig                         1.1.1
intake                            2.0.7
intervaltree                      3.1.0
ipykernel                         6.28.0
ipython                           8.27.0
ipython-genutils                  0.2.0
ipywidgets                        7.8.1
isoduration                       20.11.0
isort                             5.13.2
itemadapter                       0.3.0
itemloaders                       1.1.0
itsdangerous                      2.2.0
jaraco.classes                    3.2.1
jedi                              0.19.1
jellyfish                         1.0.1
Jinja2                            3.1.4
jmespath                          1.0.1
joblib                            1.4.2
json5                             0.9.6
jsonpatch                         1.33
jsonpointer                       2.1
jsonschema                        4.23.0
jsonschema-specifications         2023.7.1
jupyter                           1.0.0
jupyter_client                    8.6.0
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.0
jupyter_server                    2.14.1
jupyter_server_terminals          0.4.4
jupyterlab                        4.2.5
jupyterlab-pygments               0.1.2
jupyterlab_server                 2.27.3
jupyterlab-widgets                1.0.0
keyring                           24.3.1
kiwisolver                        1.4.4
lazy_loader                       0.4
lazy-object-proxy                 1.10.0
lckr_jupyterlab_variableinspector 3.1.0
libarchive-c                      5.1
libmambapy                        1.5.8
lightning-utilities               0.15.2
linkify-it-py                     2.0.0
llvmlite                          0.43.0
lmdb                              1.4.1
locket                            1.0.0
logical-unification               0.4.6
lxml                              5.2.1
lz4                               4.3.2
Mako                              1.2.3
Markdown                          3.4.1
markdown-it-py                    2.2.0
MarkupSafe                        2.1.3
matplotlib                        3.9.2
matplotlib-inline                 0.1.6
mayavi                            4.8.3
mccabe                            0.7.0
mdit-py-plugins                   0.3.0
mdurl                             0.1.0
menuinst                          2.1.2
miniKanren                        1.0.5
mistune                           2.0.4
more-itertools                    10.3.0
mpmath                            1.3.0
msgpack                           1.0.3
multidict                         6.0.4
multimethod                       1.12
multipledispatch                  0.6.0
mypy                              1.11.2
mypy-extensions                   1.0.0
narwhals                          2.5.0
navigator-updater                 0.5.1
nb_conda_kernels                  2.5.2
nbclient                          0.8.0
nbconvert                         7.16.4
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.3
nfoursid                          1.0.2
nltk                              3.9.1
notebook                          7.2.2
notebook_shim                     0.2.3
numba                             0.60.0
numexpr                           2.8.7
numpy                             1.26.4
numpydoc                          1.7.0
openpyxl                          3.1.5
opt_einsum                        3.4.0
overrides                         7.4.0
packaging                         24.1
pandas                            2.3.0
pandocfilters                     1.5.0
panel                             1.5.2
param                             2.1.1
parsel                            1.8.1
parso                             0.8.3
partd                             1.4.1
pathspec                          0.10.3
patsy                             0.5.6
pexpect                           4.8.0
pgmpy                             1.0.0
phik                              0.12.5
pickleshare                       0.7.5
pillow                            10.4.0
pip                               24.2
pkce                              1.0.3
pkginfo                           1.10.0
platformdirs                      3.10.0
plotly                            5.24.1
pluggy                            1.0.0
ply                               3.11
prometheus-client                 0.14.1
prompt-toolkit                    3.0.43
Protego                           0.1.16
protobuf                          4.25.3
psutil                            5.9.0
ptyprocess                        0.7.0
pure-eval                         0.2.2
puremagic                         1.30
py-cpuinfo                        9.0.0
pyAgrum                           2.2.1
pyaml                             25.7.0
pyarrow                           16.1.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pybbn                             3.2.3
pycodestyle                       2.11.1
pycosat                           0.6.6
pycparser                         2.21
pyct                              0.5.0
pycurl                            7.45.3
pydantic                          2.8.2
pydantic_core                     2.20.1
pydantic-settings                 2.6.1
pydataset                         0.2.0
pydeck                            0.8.0
PyDispatcher                      2.0.5
pydocstyle                        6.3.0
pydot                             4.0.1
pyeph                             1.4.0
pyerfa                            2.0.1.4
pyface                            8.0.0
pyflakes                          3.2.0
Pygments                          2.15.1
PyJWT                             2.8.0
pylint                            2.16.2
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
pymc                              5.25.1
pyobjc-core                       10.1
pyobjc-framework-Cocoa            10.1
pyobjc-framework-CoreServices     10.1
pyobjc-framework-FSEvents         10.1
pyod                              2.0.5
pyodbc                            5.1.0
pyOpenSSL                         24.2.1
pyparsing                         3.1.2
PyQt5                             5.15.10
PyQt5-sip                         12.13.0
PyQtWebEngine                     5.15.6
pyro-api                          0.1.2
pyro-ppl                          1.9.1
PySocks                           1.7.1
pytensor                          2.31.7
pytest                            7.4.4
python-dateutil                   2.9.0.post0
python-dotenv                     0.21.0
python-json-logger                2.0.7
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-server                 1.10.0
python-slugify                    5.0.2
pytoolconfig                      1.2.6
pytorch-lightning                 2.5.2
pytz                              2024.1
pyviz_comms                       3.0.2
PyWavelets                        1.7.0
PyYAML                            6.0.1
pyzmq                             25.1.2
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.3.1
qtconsole                         5.5.1
QtPy                              2.4.1
queuelib                          1.6.2
rasterio                          1.4.3
readchar                          4.0.5
referencing                       0.30.2
regex                             2024.9.11
requests                          2.32.3
requests-file                     1.5.1
requests-toolbelt                 1.0.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.7.1
rope                              1.12.0
rpds-py                           0.10.6
Rtree                             1.0.1
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruamel-yaml-conda                 0.17.21
s3fs                              2024.6.1
scikit-image                      0.24.0
scikit-learn                      1.7.2
scikit-optimize                   0.10.2
scipy                             1.13.1
Scrapy                            2.11.1
seaborn                           0.13.2
semver                            3.0.2
Send2Trash                        1.8.2
sentry-sdk                        2.18.0
service-identity                  18.1.0
setuptools                        75.1.0
shap                              0.48.0
shellingham                       1.5.0
sip                               6.7.12
six                               1.16.0
slicer                            0.0.8
smart-open                        5.2.1
smmap                             4.0.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            7.3.7
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.10
spyder                            5.5.1
spyder-kernels                    2.5.0
SQLAlchemy                        2.0.34
stack-data                        0.2.0
statsforecast                     2.0.2
statsmodels                       0.14.2
streamlit                         1.37.1
sweetviz                          2.3.1
sympy                             1.13.2
tables                            3.10.1
tabulate                          0.9.0
tblib                             1.7.0
tenacity                          8.2.3
tensorboardX                      2.6.4
terminado                         0.17.1
text-unidecode                    1.3
textdistance                      4.2.1
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2023.4.12
tinycss2                          1.2.1
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.11.1
toolz                             0.12.0
torch                             2.2.2
torchmetrics                      1.8.2
tornado                           6.4.1
tqdm                              4.66.5
traitlets                         5.14.3
traits                            7.0.2
traitsui                          8.0.0
triad                             0.9.8
truststore                        0.8.0
Twisted                           23.10.0
typeguard                         4.4.4
typer                             0.9.0
typing_extensions                 4.14.1
tzdata                            2023.3
uc-micro-py                       1.0.1
ujson                             5.10.0
unicodedata2                      15.1.0
Unidecode                         1.3.8
uri-template                      1.3.0
urllib3                           2.2.3
utilsforecast                     0.2.12
visions                           0.8.1
vtk                               9.5.0
w3lib                             2.1.2
watchdog                          4.0.1
wcwidth                           0.2.5
webcolors                         24.11.1
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.0.3
wget                              3.2
whatthepatch                      1.0.2
wheel                             0.44.0
widgetsnbextension                3.6.6
wordcloud                         1.9.4
wrapt                             1.14.1
wurlitzer                         3.0.2
xarray                            2025.8.0
xarray-einstats                   0.9.1
xgboost                           3.0.5
xlrd                              2.0.2
xlwings                           0.32.1
xyzservices                       2022.9.0
yapf                              0.40.2
yarl                              1.11.0
ydata-profiling                   4.16.1
zict                              3.0.0
zipp                              3.17.0
zope.interface                    5.4.0
zstandard                         0.23.0

In [7]:
!pip install surprise
# https://surprise.readthedocs.io/

Collecting surprise
  Downloading surprise-0.1-py2.py3-none-any.whl.metadata (327 bytes)
Collecting scikit-surprise (from surprise)
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-surprise->surprise) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-surprise->surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-surprise->surprise) (1.13.1)
Downloading surprise-0.1-py2.py3-none-any.whl (1.8 kB)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp312-cp312-macosx_10_15_x86_64.whl size=493047 sha256=84a5f7b90593e72732ac4b04bd5d52773cbe306fffff3fb8c0c6b14679ba9501
  Stored in directory: /Users/abc/Library/Caches/pip/wheels/75/fa/bc/739bc2cb1fbaab6061854e6cfbb81a0ae52c92a502a7fa454b
Successfully built scikit-surprise
Installing collected packages: scikit-surprise, surprise
Successfully installed scikit-surprise-1.1.4 surprise-0.1

In [8]:
# Bajamos el dataset. En windows pueden descargarlo entrando al link manualmente
#!wget https://files.grouplens.org/datasets/movielens/ml-100k/u.data

In [9]:
# información sobre Movie lens https://files.grouplens.org/datasets/movielens/ml-100k-README.txt

mlens = pd.read_csv("https://files.grouplens.org/datasets/movielens/ml-100k/u.data",sep="\t",header=None)
mlens.columns = ["user_id","item_id","rating","timestamp"]
mlens

       user_id  item_id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [10]:
len(mlens['user_id'].unique())

943

In [11]:
len(mlens['item_id'].unique())

1682

In [12]:
mlens.drop("timestamp", axis=1, inplace=True)

In [13]:
mlens

       user_id  item_id  rating
0          196      242       3
1          186      302       3
2           22      377       1
3          244       51       2
4          166      346       1
...        ...      ...     ...
99995      880      476       3
99996      716      204       5
99997      276     1090       1
99998       13      225       2
99999       12      203       3

[100000 rows x 3 columns]

El paquete surprise no recibe directamente un objeto DataFrame.
Para parsear y leer un conjunto de datos debe hacerlo a través de dos nuevos objetos: Reader y Dataset.
En Reader debemos especificar el valor mínimo y el valor máximo de los ratings.
Dataset nos permite leer datos desde distintas fuentes.

In [ ]:
from surprise import Dataset, Reader

# Creamos un objeto Reader indicando el rango de las valoraciones (ratings).
# mlens["rating"].min() → obtiene el valor mínimo de la columna "rating"
# mlens["rating"].max() → obtiene el valor máximo de la columna "rating"
# Esto asegura que el sistema entienda cuál es el rango válido de puntuaciones.
reader = Reader(rating_scale=(mlens["rating"].min(), mlens["rating"].max()))

In [15]:
dataset = Dataset.load_from_df(mlens,reader)
dataset

Ahora cargue SVD y GridSearchCV, ambos de surprise.

In [ ]:
from surprise import SVD
from surprise.model_selection.search import GridSearchCV

"\nclasssurprise.prediction_algorithms.matrix_factorization.SVD(n_factors=100,\nn_epochs=20, biased=True, init_mean=0, init_std_dev=0.1, lr_all=0.005, reg_all=0.02,\nlr_bu=None, lr_bi=None, lr_pu=None, lr_qi=None, reg_bu=None, reg_bi=None,\nreg_pu=None, reg_qi=None, random_state=None, verbose=False)\n\nclass surprise.model_selection.search.GridSearchCV(algo_class, param_grid,\nmeasures=['rmse', 'mae'], cv=None, refit=False, return_train_measures=False,\nn_jobs=1, pre_dispatch='2*n_jobs', joblib_verbose=0)\n"

Genere una grilla de parámetros donde se prueben distintas combinaciones de:  
  - epochs: es la cantidad de pasadas sobre el dataset que hará el algoritmo empleando descenso por el gradiente  
  - biased: usar parámetros de sesgo o no  
  - lr_all: learning rate para todos los parámetros  
  - reg_all: término de regularización para todos los parámetros (lambda)

In [17]:
param_grid = {'n_epochs': [5, 10], 'lr_all': [0.002, 0.005], 'reg_all': [0.4, 0.6]}

Emplee GridSearchCV, SVD y el diccionario con los parámetros para probar, y entrene un modelo. Note que a GridSearchCV necesita pasarle un modelo sin instanciar. Además, setee el parámetro refit a True y con measures = ["rmse","fcp"]

In [ ]:
# Definimos un diccionario con los hiperparámetros que vamos a probar en el modelo
param_grid = {
    'n_epochs': [5, 10],     # ⏳ Número de épocas (iteraciones de entrenamiento) a probar: 5 o 10
    'lr_all': [0.002, 0.005],# 📈 Tasa de aprendizaje para todos los parámetros (qué tan rápido ajusta el modelo)
    'reg_all': [0.4, 0.6]    # ⚖️ Factor de regularización (controla el sobreajuste) a probar: 0.4 o 0.6
}

In [19]:
gs.fit(dataset)

Imprima el rmse y el fcp, y la mejor combinación de parámetros

In [20]:
gs.best_score

{'fcp': 0.6993020842452041, 'rmse': 0.963905867924563}

In [ ]:
gs.best_params

{
    'fcp': {                     # 📊 Mejores parámetros encontrados para la métrica FCP (Fraction of Concordant Pairs)
        'n_epochs': 10,          # ⏳ Número de épocas = 10
        'lr_all': 0.005,         # 📈 Tasa de aprendizaje = 0.005
        'reg_all': 0.6           # ⚖️ Regularización = 0.6
    },
    'rmse': {                    # 📉 Mejores parámetros encontrados para la métrica RMSE (Root Mean Squared Error)
        'n_epochs': 10,          # ⏳ Número de épocas = 10
        'lr_all': 0.005,         # 📈 Tasa de aprendizaje = 0.005
        'reg_all': 0.4           # ⚖️ Regularización = 0.4
    }
}

{'fcp': {'n_epochs': 10, 'lr_all': 0.005, 'reg_all': 0.6},
 'rmse': {'n_epochs': 10, 'lr_all': 0.005, 'reg_all': 0.4}}

Guarde el modelo con mayor fcp y prediga el rating para el user id 196 e item id 242

In [22]:
best_model = gs.best_estimator["fcp"]

In [23]:
pred = best_model.predict("196", "242")
pred

Prediction(uid='196', iid='242', r_ui=None, est=3.52986, details={'was_impossible': False})

In [24]:
pred.est

3.52986

Pruebe empleando otros modelos como SVDpp,  NMF,  KNNWithZScore e intente superar el valor obtenido

In [25]:
from surprise import SVDpp

'''
class surprise.prediction_algorithms.matrix_factorization.SVDpp(n_factors=20, n_epochs=20,
init_mean=0, init_std_dev=0.1, lr_all=0.007, reg_all=0.02, lr_bu=None, lr_bi=None,
lr_pu=None, lr_qi=None, lr_yj=None, reg_bu=None, reg_bi=None, reg_pu=None, reg_qi=None,
reg_yj=None, random_state=None, verbose=False, cache_ratings=False)
'''

gs1 = GridSearchCV(SVDpp, param_grid, measures=['fcp',"rmse"], cv=3, refit=True)
gs1.fit(dataset)
gs1.best_score

{'fcp': 0.6985723171062354, 'rmse': 0.963834874126817}

In [ ]:
from surprise import NMF

'''
class surprise.prediction_algorithms.matrix_factorization.NMF(n_factors=15, n_epochs=50,
biased=False, reg_pu=0.06, reg_qi=0.06, reg_bu=0.02, reg_bi=0.02, lr_bu=0.005,
lr_bi=0.005, init_low=0, init_high=1, random_state=None, verbose=False)
'''

param_grid2 = {
    'n_epochs': [5, 10],     # ⏳ número de iteraciones: 5 o 10
    'lr_bu': [0.002, 0.005], # 📈 tasa de aprendizaje de sesgo de usuarios
    'lr_bi': [0.002, 0.005], # 📈 tasa de aprendizaje de sesgo de ítems
    'reg_pu': [0.04, 0.06],  # ⚖️ regularización de factores de usuario
    'reg_qi': [0.04, 0.06],  # ⚖️ regularización de factores de ítem
    'reg_bu': [0.01, 0.03],  # ⚖️ regularización del sesgo de usuario
    'reg_bi': [0.01, 0.03]   # ⚖️ regularización del sesgo de ítem
}


# 🔹 Configuramos GridSearchCV de Surprise:
gs2 = GridSearchCV(NMF, param_grid2, measures=['fcp', 'rmse'], cv=3, refit=True)

# 🔹 Entrenamos la búsqueda de hiperparámetros con el dataset
gs2.fit(dataset)

# 🔹 Obtenemos los mejores scores alcanzados en cada métrica
gs2.best_score

{'fcp': 0.6807268770144659, 'rmse': 0.9994562283774995}

In [27]:
from surprise import KNNWithZScore

'''
classsurprise.prediction_algorithms.knns.KNNWithZScore(k=40, min_k=1,
sim_options={}, verbose=True, **kwargs)
'''
param_grid3={'k': range(20, 65,5)}
gs3 = GridSearchCV(KNNWithZScore, param_grid3, measures=['fcp',"rmse"], cv=3, refit=True)
gs3.fit(dataset)
gs3.best_score

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.

{'fcp': 0.705360284098843, 'rmse': 0.9558750271831403}

# Recomendación basada en el contenido

En este ejemplo vamos a tomar un corpus de textos de autores latinoamericanos para sugerir uno similar a uno dado. Para esto construiremos una matriz TFIDF, de frecuencias normalizadas de términos por documento, y usaremos la similitud coseno para medir distancias entre los distintos textos.

In [28]:
!git clone https://github.com/karen-pal/borges

Cloning into 'borges'...
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (328/328), done.
remote: Compressing objects: 100% (264/264), done.
remote: Total 328 (delta 131), reused 249 (delta 60), pack-reused 0 (from 0)
Receiving objects: 100% (328/328), 26.76 MiB | 7.73 MiB/s, done.
Resolving deltas: 100% (131/131), done.

In [29]:
!ls

1 - Presentación Sistemas de Recomendación.pdf
Sistemas_Recomendacion_Github.ipynb
borges
sistemas_recomendacion_surprise.ipynb

In [30]:
!cd borges
!ls borges/

LDA.ipynb                 datasets                  scraper.py
README.md                 full_text_scrapper.py     sentence_similarity.ipynb
borges.ipynb              link_scrapper.py          uso_simple.ipynb

In [31]:
!ls borges/datasets

borges_sentiment_corpus.csv full_corpus.csv
datasets_csv                links
datasets_pkl                pkl_to_csv.ipynb

In [32]:
import pickle
from pathlib import Path
import pandas as pd

df = pd.DataFrame()
# usando el asterisco de "wildcard" traemos todos los archivos en formato pickle
pkls = Path('.').glob('./borges/datasets/datasets_pkl/*texts.pkl')

# leemos todos los pickles y concatenarlos en un DataFrame
for pkl in pkls:
    with open(pkl, 'rb') as inp:
        df_ = pickle.load(inp)
    df = pd.concat([df, df_])

df.shape

(719, 3)

In [33]:
df

,link,text_metadata,text
0,https://ciudadseva.com/texto/la-hija-del-guard...,"{'title': 'La hija del guardaagujas', 'metadat...",La casita del guardaagujas está junto a la lín...
1,https://ciudadseva.com/texto/la-joven-del-abri...,"{'title': 'La joven del abrigo largo', 'metada...",Cruza todos los días la plaza en el mismo sent...
2,https://ciudadseva.com/texto/tragedia/,"{'title': 'Tragedia', 'metadata': '[Minicuento...",María Olga es una mujer encantadora. Especialm...
0,https://ciudadseva.com/texto/azogue/,"{'title': 'Azogue', 'metadata': '[Minicuento -...",Pobrecita Alicia. Aunque la razón te decía no ...
1,https://ciudadseva.com/texto/casa-di-amore-e-p...,"{'title': 'Casa di Amore e Psyche', 'metadata'...","Pero qué maravilla, qué maravilla, decía la se..."
...,...,...,...
0,https://ciudadseva.com/texto/en-el-insomnio/,"{'title': 'En el insomnio', 'metadata': '[Mini...",El hombre se acuesta temprano. No puede concil...
1,https://ciudadseva.com/texto/la-carne/,"{'title': 'La carne', 'metadata': '[Cuento - T...","Sucedió con gran sencillez, sin afectación. Po..."
2,https://ciudadseva.com/texto/natacion/,"{'title': 'Natación', 'metadata': '[Minicuento...",He aprendido a nadar en seco. Resulta más vent...
0,https://ciudadseva.com/texto/el-tren-dabove/,"{'title': 'El tren', 'metadata': '[Cuento - Te...","El tren era todos los días a la tardecita, per..."
1,https://ciudadseva.com/texto/ser-polvo/,"{'title': 'Ser polvo', 'metadata': '[Cuento - ...",¡Inexorable severidad de las circunstancias! L...

In [34]:
df['text_metadata'].sample(2)

15    {'title': 'Nube de polillas', 'metadata': '[Mi...
17    {'title': 'La gloriosa', 'metadata': '[Minicue...
Name: text_metadata, dtype: object

In [35]:
df.columns

Index(['link', 'text_metadata', 'text'], dtype='object')

In [36]:
# separamos de la metadata el título y autor en sus propias columnas
df['title'] = df['text_metadata'].apply(lambda x: x['title'])
df['author'] = df['text_metadata'].apply(lambda x: x['author'])

In [37]:
# vemos los autores disponibloes
df['author'].value_counts()

author
Jorge Luis Borges             60
Julio Cortázar                55
Baldomero Lillo               50
Juan José Arreola             45
Augusto Monterroso            45
Alfonso Reyes                 37
Enrique Anderson Imbert       36
Mario Benedetti               33
Julio Ramón Ribeyro           27
Roberto Arlt                  25
Clarice Lispector             25
Julio Torri                   23
Felisberto Hernández          15
Luis Vidales                  14
Adolfo Bioy Casares           13
Rubén Darío                   13
Álvaro Mutis                  11
Juan Rulfo                    10
Juan Rodolfo Wilcock          10
Edmundo Valadés               10
Elena Garro                    9
Manuel A. Alonso               9
Salarrué                       9
Juan Bosch                     8
Eduardo Gudiño Kieffer         8
Alejo Carpentier               8
Silvina Ocampo                 7
Virgilio Díaz Grullón          7
Andrés Rivera                  7
Rodolfo Walsh                  6
Ricardo Güiraldes              6
Manuel Romero de Terreros      5
José Donoso                    5
Pablo Palacio                  5
Julio Garmendia                4
Gregorio López y Fuentes       4
[Cuento - Texto completo.]     4
Macedonio Fernández            3
Amparo Dávila                  3
Rómulo Gallegos                3
Inés Arredondo                 3
José Edwards                   3
José María Arguedas            3
José Lezama Lima               3
Sergio Pitol                   3
Octavio Paz                    3
Virgilio Piñera                3
Rubén Bareiro Saguier          3
María Luisa Bombal             3
Vicente Huidobro               3
Leonora Carrington             2
Teresa de la Parra             2
Humberto Arenal                2
Santiago Dabove                2
Carmen Lyra                    1
Esteban Echeverría             1
Manuel González Zeledón        1
Ricardo Jaimes Freyre          1
Name: count, dtype: int64

In [38]:
# quitamos duplicados y reiniciamos el índice
df = df.drop_duplicates(subset=[c for c in df.columns if c != 'text_metadata'])
df = df.reset_index(drop=True)
df.shape

(693, 5)

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel
from pprint import pprint

Vamos a calcular las matrices de ocurrencias de términos usando sklearn.

Ámbas clases primero construyen el vocabulario total, y luego:  
- **CountVectorizer** nos devuelve la frecuencia absoluta de cada término por cada documento.
- [**TF-IDF**](https://en.wikipedia.org/wiki/Tf%E2%80%93idf): calcula la frecuencia de cada término por documento, y normaliza por el total de documentos donde el término aparece.

$${tf} (t,d)={\frac {f_{t,d}}{\sum _{t'\in d}{f_{t',d}}}}$$

$$
idf( t, D ) = log \frac{ \text{| } D \text{ |} }{ 1 + \text{| } \{ d \in D : t \in d \} \text{ |} }
$$


$$ tfidf( t, d, D ) = tf( t, d ) \times idf( t, D )
$$

In [ ]:
# Instanciamos el CV
vectorizer = CountVectorizer()

doc1 = 'la matriz de frecuencias por palabras otorga información del contenido de un documento'
doc2 = 'las palabras que aparecen en un documento se relaciona con su tema'
# Definimos una lista con todos los strings
data_corpus = [doc1, doc2]

# Fiteamos el CV y transformamos los datos
X = vectorizer.fit_transform(data_corpus)
# 👉 fit_transform hace dos cosas:
# Aprende el vocabulario (palabras únicas en todos los documentos).
# Transforma cada documento en un vector con las frecuencias de esas palabras.
# El resultado X es una sparse matrix (matriz dispersa), eficiente en memoria.

# Pasamos de sparse matrix a array usando .toarray()

print(X.toarray())
# Usando el metodo .get_feature_names() del CV podemos acceder al indice de palabras
print(vectorizer.get_feature_names_out())

[[0 0 1 2 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1]
 [1 1 0 0 0 1 1 0 0 0 1 0 0 1 0 1 1 1 1 1 1]]
['aparecen' 'con' 'contenido' 'de' 'del' 'documento' 'en' 'frecuencias'
 'información' 'la' 'las' 'matriz' 'otorga' 'palabras' 'por' 'que'
 'relaciona' 'se' 'su' 'tema' 'un']

In [41]:
X

<2x21 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [42]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop = list(stopwords.words('spanish'))
# eliminamos las "stop words", palabras comunes no informativas
tf = TfidfVectorizer(stop_words=stop)

[nltk_data] Downloading package stopwords to /Users/abc/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [43]:
# calculamos los features para cada ítem (texto)
tfidf_matrix = tf.fit_transform(df['text'])

In [44]:
tfidf_matrix.shape

(693, 56608)

In [45]:
# calculamos las similitudes entre todos los documentos
cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)
n = 6

# diccionario creado para guardar el resultado en un formato (autor - titulo : puntaje, titulo, autor)
results = {}
for idx, row in df.iterrows():
    # guardamos los indices similares basados en la similitud coseno. Los ordenamos en modo ascendente, siendo 0 nada de similitud y 1 total
    similar_indices = cosine_similarities[idx].argsort()[:-n-2:-1]
    # guardamos los N más cercanos
    similar_items = [(f"{df['author'][i]} - {df['title'][i]}", round(cosine_similarities[idx][i], 3)) for i in similar_indices]
    results[f"{row['author']} - {row['title']}"] = similar_items[1:]

In [46]:
pprint(results['Jorge Luis Borges - El Aleph'])

[('Jorge Luis Borges - La escritura del dios', 0.144),
 ('Jorge Luis Borges - El inmortal', 0.135),
 ('Jorge Luis Borges - Utopía de un hombre que está cansado', 0.125),
 ('Felisberto Hernández - El acomodador', 0.122),
 ('Clarice Lispector - La búsqueda de la dignidad', 0.121),
 ('Jorge Luis Borges - Funes el memorioso', 0.11)]

In [47]:
def recomendar(autor, titulo):
    pprint(results[f"{autor} - {titulo}"])

In [48]:
recomendar('Julio Cortázar', 'Axolotl')

[('Felisberto Hernández - El acomodador', 0.134),
 ('Felisberto Hernández - El cocodrilo', 0.101),
 ('Felisberto Hernández - Menos Julia', 0.089),
 ('Julio Cortázar - Después del almuerzo', 0.088),
 ('Julio Cortázar - La noche boca arriba', 0.086),
 ('Julio Cortázar - La señorita Cora', 0.086)]

In [49]:
# https://medium.com/@eng.saavedra/sistemas-de-recomendaci%C3%B3n-parte-2-b8a5dc9dc730
# https://towardsdatascience.com/item-based-collaborative-filtering-in-python-91f747200fab
# https://www.genbeta.com/web/asi-funcionan-las-recomendaciones-de-amazon